# Postgres
spring:
  config.activate.on-profile: prod
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
    show-sql: true

---
spring:
  config.activate.on-profile: test,dev
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
